### ISSUE TITLE
Logo proposal for recordariumAPP

### ISSUE THREAD

**Issue by zuurw** [eduardorasgado/recordariumApp#1]
Hi, @eduardorasgado  I'd like to collaborate on this open source project and propose free logo/icon design for this project. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by eduardorasgado** [comment]
@zuurw sure dude! This is a finished app and I dont have a logo, This app reminds you for your pills, like a daily alarm :clock1:  :) I like your work, try to work on this. You're welcome! Thanks.

**Comment by zuurw** [comment]
Hi @eduardorasgado, here is the design that I create for this project, so for the concept I design 1st a pill and then add a bell as a reference an alarm ou alert to take the pills.
I hope you like it.

Cheers!

![proposal](https://user-images.githubusercontent.com/40801473/43133057-81bc2106-8f35-11e8-9fdd-d7ad5d3b6ab0.png)

**Comment by eduardorasgado** [comment]
Good job mate! I think the blue design is a good one for the project. Your welcome to send me a PR :100:

**Comment by zuurw** [comment]
Job done!

Best Regards!
